const ISO_MAP = {
  "aa": { "code2": "aar", "name": "Afar" },
  "ab": { "code2": "abk", "name": "Abkhazian" },
  "ace": { "code2": "ace", "name": "Achinese" },
  "ach": { "code2": "ach", "name": "Acoli" },
  "ada": { "code2": "ada", "name": "Adangme" },
  "ady": { "code2": "ady", "name": "Adyghe" },
  "ae": { "code2": "ave", "name": "Avestan" },
  "af": { "code2": "afr", "name": "Afrikaans" },
  "afh": { "code2": "afh", "name": "Afrihili" },
  "agq": { "code2": "agq", "name": "Aghem" },
  "ain": { "code2": "ain", "name": "Ainu" },
  "ak": { "code2": "aka", "name": "Akan" },
  "akk": { "code2": "akk", "name": "Akkadian" },
  "ale": { "code2": "ale", "name": "Aleut" },
  "alt": { "code2": "alt", "name": "Southern Altai" },
  "am": { "code2": "amh", "name": "Amharic" },
  "an": { "code2": "arg", "name": "Aragonese" },
  "ang": { "code2": "ang", "name": "Old English" },
  "anp": { "code2": "anp", "name": "Angika" },
  "ar": { "code2": "ara", "name": "Arabic" },
  "arc": { "code2": "arc", "name": "Aramaic" },
  "arn": { "code2": "arn", "name": "Mapuche" },
  "arp": { "code2": "arp", "name": "Arapaho" },
  "arw": { "code2": "arw", "name": "Arawak" },
  "as": { "code2": "asm", "name": "Assamese" },
  "asa": { "code2": "asa", "name": "Asu" },
  "ast": { "code2": "ast", "name": "Asturian" },
  "av": { "code2": "ava", "name": "Avaric" },
  "awa": { "code2": "awa", "name": "Awadhi" },
  "ay": { "code2": "aym", "name": "Aymara" },
  "az": { "code2": "aze", "name": "Azerbaijani" },
  "ba": { "code2": "bak", "name": "Bashkir" },
  "bal": { "code2": "bal", "name": "Baluchi" },
  "ban": { "code2": "ban", "name": "Balinese" },
  "bas": { "code2": "bas", "name": "Basaa" },
  "be": { "code2": "bel", "name": "Belarusian" },
  "bej": { "code2": "bej", "name": "Beja" },
  "bem": { "code2": "bem", "name": "Bemba" },
  "bez": { "code2": "bez", "name": "Bena" },
  "bg": { "code2": "bul", "name": "Bulgarian" },
  "bgn": { "code2": "bgn", "name": "Western Balochi" },
  "bh": { "code2": "bih", "name": "Bihari" },
  "bho": { "code2": "bho", "name": "Bhojpuri" },
  "bi": { "code2": "bis", "name": "Bislama" },
  "bik": { "code2": "bik", "name": "Bikol" },
  "bin": { "code2": "bin", "name": "Bini" },
  "bla": { "code2": "bla", "name": "Siksika" },
  "bm": { "code2": "bam", "name": "Bambara" },
  "bn": { "code2": "ben", "name": "Bengali" },
  "bo": { "code2": "bod", "name": "Tibetan" },
  "br": { "code2": "bre", "name": "Breton" },
  "bra": { "code2": "bra", "name": "Braj" },
  "brx": { "code2": "brx", "name": "Bodo" },
  "bs": { "code2": "bos", "name": "Bosnian" },
  "bua": { "code2": "bua", "name": "Buriat" },
  "bug": { "code2": "bug", "name": "Buginese" },
  "byn": { "code2": "byn", "name": "Blin" },
  "ca": { "code2": "cat", "name": "Catalan" },
  "cad": { "code2": "cad", "name": "Caddo" },
  "car": { "code2": "car", "name": "Carib" },
  "cay": { "code2": "cay", "name": "Cayuga" },
  "cch": { "code2": "cch", "name": "Atsam" },
  "ce": { "code2": "che", "name": "Chechen" },
  "ceb": { "code2": "ceb", "name": "Cebuano" },
  "cgg": { "code2": "cgg", "name": "Chiga" },
  "ch": { "code2": "cha", "name": "Chamorro" },
  "chb": { "code2": "chb", "name": "Chibcha" },
  "chg": { "code2": "chg", "name": "Chagatai" },
  "chk": { "code2": "chk", "name": "Chuukese" },
  "chm": { "code2": "chm", "name": "Mari" },
  "chn": { "code2": "chn", "name": "Chinook Jargon" },
  "cho": { "code2": "cho", "name": "Choctaw" },
  "chp": { "code2": "chp", "name": "Chipewyan" },
  "chr": { "code2": "chr", "name": "Cherokee" },
  "chy": { "code2": "chy", "name": "Cheyenne" },
  "ckb": { "code2": "ckb", "name": "Central Kurdish" },
  "co": { "code2": "cos", "name": "Corsican" },
  "cop": { "code2": "cop", "name": "Coptic" },
  "cr": { "code2": "cre", "name": "Cree" },
  "crh": { "code2": "crh", "name": "Crimean Turkish" },
  "cs": { "code2": "ces", "name": "Czech" },
  "csb": { "code2": "csb", "name": "Kashubian" },
  "cu": { "code2": "chu", "name": "Church Slavic" },
  "cv": { "code2": "chv", "name": "Chuvash" },
  "cy": { "code2": "cym", "name": "Welsh" },
  "da": { "code2": "dan", "name": "Danish" },
  "dak": { "code2": "dak", "name": "Dakota" },
  "dar": { "code2": "dar", "name": "Dargwa" },
  "dav": { "code2": "dav", "name": "Taita" },
  "de": { "code2": "deu", "name": "German" },
  "del": { "code2": "del", "name": "Delaware" },
  "den": { "code2": "den", "name": "Slave" },
  "dgr": { "code2": "dgr", "name": "Dogrib" },
  "din": { "code2": "din", "name": "Dinka" },
  "dje": { "code2": "dje", "name": "Zarma" },
  "doi": { "code2": "doi", "name": "Dogri" },
  "dsb": { "code2": "dsb", "name": "Lower Sorbian" },
  "dua": { "code2": "dua", "name": "Duala" },
  "dum": { "code2": "dum", "name": "Middle Dutch" },
  "dv": { "code2": "div", "name": "Divehi" },
  "dyo": { "code2": "dyo", "name": "Jola-Fonyi" },
  "dyu": { "code2": "dyu", "name": "Dyula" },
  "dz": { "code2": "dzo", "name": "Dzongkha" },
  "ebu": { "code2": "ebu", "name": "Embu" },
  "ee": { "code2": "ewe", "name": "Ewe" },
  "efi": { "code2": "efi", "name": "Efik" },
  "egy": { "code2": "egy", "name": "Ancient Egyptian" },
  "eka": { "code2": "eka", "name": "Ekajuk" },
  "el": { "code2": "ell", "name": "Greek" },
  "elx": { "code2": "elx", "name": "Elamite" },
  "en": { "code2": "eng", "name": "English" },
  "enm": { "code2": "enm", "name": "Middle English" },
  "eo": { "code2": "epo", "name": "Esperanto" },
  "es": { "code2": "spa", "name": "Spanish" },
  "et": { "code2": "est", "name": "Estonian" },
  "eu": { "code2": "eus", "name": "Basque" },
  "ewo": { "code2": "ewo", "name": "Ewondo" },
  "fa": { "code2": "fas", "name": "Persian" },
  "fan": { "code2": "fan", "name": "Fang" },
  "fat": { "code2": "fat", "name": "Fanti" },
  "ff": { "code2": "ful", "name": "Fulah" },
  "fi": { "code2": "fin", "name": "Finnish" },
  "fil": { "code2": "fil", "name": "Filipino" },
  "fj": { "code2": "fij", "name": "Fijian" },
  "fo": { "code2": "fao", "name": "Faroese" },
  "fon": { "code2": "fon", "name": "Fon" },
  "fr": { "code2": "fra", "name": "French" },
  "frm": { "code2": "frm", "name": "Middle French" },
  "fro": { "code2": "fro", "name": "Old French" },
  "frr": { "code2": "frr", "name": "Northern Frisian" },
  "frs": { "code2": "frs", "name": "Eastern Frisian" },
  "fur": { "code2": "fur", "name": "Friulian" },
  "fy": { "code2": "fry", "name": "Western Frisian" },
  "ga": { "code2": "gle", "name": "Irish" },
  "gaa": { "code2": "gaa", "name": "Ga" },
  "gag": { "code2": "gag", "name": "Gagauz" },
  "gay": { "code2": "gay", "name": "Gayo" },
  "gba": { "code2": "gba", "name": "Gbaya" },
  "gd": { "code2": "gla", "name": "Scottish Gaelic" },
  "gez": { "code2": "gez", "name": "Geez" },
  "gil": { "code2": "gil", "name": "Gilbertese" },
  "gl": { "code2": "glg", "name": "Galician" },
  "gmh": { "code2": "gmh", "name": "Middle High German" },
  "gn": { "code2": "grn", "name": "Guarani" },
  "goh": { "code2": "goh", "name": "Old High German" },
  "gon": { "code2": "gon", "name": "Gondi" },
  "gor": { "code2": "gor", "name": "Gorontalo" },
  "got": { "code2": "got", "name": "Gothic" },
  "grb": { "code2": "grb", "name": "Grebo" },
  "grc": { "code2": "grc", "name": "Ancient Greek" },
  "gsw": { "code2": "gsw", "name": "Swiss German" },
  "gu": { "code2": "guj", "name": "Gujarati" },
  "guz": { "code2": "guz", "name": "Gusii" },
  "gv": { "code2": "glv", "name": "Manx" },
  "gwi": { "code2": "gwi", "name": "Gwichʼin" },
  "ha": { "code2": "hau", "name": "Hausa" },
  "hai": { "code2": "hai", "name": "Haida" },
  "haw": { "code2": "haw", "name": "Hawaiian" },
  "he": { "code2": "heb", "name": "Hebrew" },
  "hi": { "code2": "hin", "name": "Hindi" },
  "hil": { "code2": "hil", "name": "Hiligaynon" },
  "hit": { "code2": "hit", "name": "Hittite" },
  "hmn": { "code2": "hmn", "name": "Hmong" },
  "ho": { "code2": "hmo", "name": "Hiri Motu" },
  "hr": { "code2": "hrv", "name": "Croatian" },
  "hsb": { "code2": "hsb", "name": "Upper Sorbian" },
  "ht": { "code2": "hat", "name": "Haitian" },
  "hu": { "code2": "hun", "name": "Hungarian" },
  "hup": { "code2": "hup", "name": "Hupa" },
  "hy": { "code2": "hye", "name": "Armenian" },
  "hz": { "code2": "her", "name": "Herero" },
  "ia": { "code2": "ina", "name": "Interlingua" },
  "iba": { "code2": "iba", "name": "Iban" },
  "id": { "code2": "ind", "name": "Indonesian" },
  "ie": { "code2": "ile", "name": "Interlingue" },
  "ig": { "code2": "ibo", "name": "Igbo" },
  "ii": { "code2": "iii", "name": "Sichuan Yi" },
  "ik": { "code2": "ipk", "name": "Inupiaq" },
  "ilo": { "code2": "ilo", "name": "Iloko" },
  "inh": { "code2": "inh", "name": "Ingush" },
  "io": { "code2": "ido", "name": "Ido" },
  "is": { "code2": "isl", "name": "Icelandic" },
  "it": { "code2": "ita", "name": "Italian" },
  "iu": { "code2": "iku", "name": "Inuktitut" },
  "ja": { "code2": "jpn", "name": "Japanese" },
  "jbo": { "code2": "jbo", "name": "Lojban" },
  "jgo": { "code2": "jgo", "name": "Ngomba" },
  "jmc": { "code2": "jmc", "name": "Machame" },
  "jv": { "code2": "jav", "name": "Javanese" },
  "ka": { "code2": "kat", "name": "Georgian" },
  "kab": { "code2": "kab", "name": "Kabyle" },
  "kac": { "code2": "kac", "name": "Kachin" },
  "kaj": { "code2": "kaj", "name": "Jju" },
  "kam": { "code2": "kam", "name": "Kamba" },
  "kau": { "code2": "kau", "name": "Kanuri" },
  "kaw": { "code2": "kaw", "name": "Kawi" },
  "kbd": { "code2": "kbd", "name": "Kabardian" },
  "kcg": { "code2": "kcg", "name": "Tyap" },
  "kde": { "code2": "kde", "name": "Makonde" },
  "kea": { "code2": "kea", "name": "Kabuverdianu" },
  "kfo": { "code2": "kfo", "name": "Koro" },
  "kg": { "code2": "kon", "name": "Kongo" },
  "kha": { "code2": "kha", "name": "Khasi" },
  "kho": { "code2": "kho", "name": "Khotanese" },
  "ki": { "code2": "kik", "name": "Kikuyu" },
  "kj": { "code2": "kua", "name": "Kuanyama" },
  "kk": { "code2": "kaz", "name": "Kazakh" },
  "kkj": { "code2": "kkj", "name": "Kako" },
  "kl": { "code2": "kal", "name": "Kalaallisut" },
  "kln": { "code2": "kln", "name": "Kalenjin" },
  "km": { "code2": "khm", "name": "Khmer" },
  "kmb": { "code2": "kmb", "name": "Kimbundu" },
  "kn": { "code2": "kan", "name": "Kannada" },
  "ko": { "code2": "kor", "name": "Korean" },
  "kok": { "code2": "kok", "name": "Konkani" },
  "kos": { "code2": "kos", "name": "Kosraean" },
  "kpe": { "code2": "kpe", "name": "Kpelle" },
  "kr": { "code2": "kau", "name": "Kanuri" },
  "krc": { "code2": "krc", "name": "Karachay-Balkar" },
  "kri": { "code2": "kri", "name": "Krio" },
  "krl": { "code2": "krl", "name": "Karelian" },
  "kru": { "code2": "kru", "name": "Kurukh" },
  "ks": { "code2": "kas", "name": "Kashmiri" },
  "ksb": { "code2": "ksb", "name": "Shambala" },
  "ksf": { "code2": "ksf", "name": "Bafia" },
  "ksh": { "code2": "ksh", "name": "Colognian" },
  "ku": { "code2": "kur", "name": "Kurdish" },
  "kum": { "code2": "kum", "name": "Kumyk" },
  "kut": { "code2": "kut", "name": "Kutenai" },
  "kv": { "code2": "kom", "name": "Komi" },
  "kw": { "code2": "cor", "name": "Cornish" },
  "ky": { "code2": "kir", "name": "Kyrgyz" },
  "la": { "code2": "lat", "name": "Latin" },
  "lad": { "code2": "lad", "name": "Ladino" },
  "lag": { "code2": "lag", "name": "Langi" },
  "lah": { "code2": "lah", "name": "Lahnda" },
  "lam": { "code2": "lam", "name": "Lamba" },
  "lb": { "code2": "ltz", "name": "Luxembourgish" },
  "lez": { "code2": "lez", "name": "Lezghian" },
  "lg": { "code2": "lug", "name": "Ganda" },
  "li": { "code2": "lim", "name": "Limburgish" },
  "lkt": { "code2": "lkt", "name": "Lakota" },
  "ln": { "code2": "lin", "name": "Lingala" },
  "lo": { "code2": "lao", "name": "Lao" },
  "lol": { "code2": "lol", "name": "Mongo" },
  "lou": { "code2": "lou", "name": "Louisiana Creole" },
  "loz": { "code2": "loz", "name": "Lozi" },
  "lt": { "code2": "lit", "name": "Lithuanian" },
  "lu": { "code2": "lub", "name": "Luba-Katanga" },
  "lua": { "code2": "lua", "name": "Luba-Lulua" },
  "lui": { "code2": "lui", "name": "Luiseno" },
  "lun": { "code2": "lun", "name": "Lunda" },
  "luo": { "code2": "luo", "name": "Luo" },
  "lus": { "code2": "lus", "name": "Mizo" },
  "luy": { "code2": "luy", "name": "Luyia" },
  "lv": { "code2": "lav", "name": "Latvian" },
  "mad": { "code2": "mad", "name": "Madurese" },
  "mag": { "code2": "mag", "name": "Magahi" },
  "mai": { "code2": "mai", "name": "Maithili" },
  "mak": { "code2": "mak", "name": "Makasar" },
  "man": { "code2": "man", "name": "Mandingo" },
  "mas": { "code2": "mas", "name": "Masai" },
  "mdf": { "code2": "mdf", "name": "Moksha" },
  "mdr": { "code2": "mdr", "name": "Mandar" },
  "men": { "code2": "men", "name": "Mende" },
  "mer": { "code2": "mer", "name": "Meru" },
  "mfe": { "code2": "mfe", "name": "Morisyen" },
  "mg": { "code2": "mlg", "name": "Malagasy" },
  "mga": { "code2": "mga", "name": "Middle Irish" },
  "mgh": { "code2": "mgh", "name": "Makhuwa-Meetto" },
  "mgo": { "code2": "mgo", "name": "Metaʼ" },
  "mh": { "code2": "mah", "name": "Marshallese" },
  "mi": { "code2": "mri", "name": "Maori" },
  "mic": { "code2": "mic", "name": "Mi'kmaq" },
  "min": { "code2": "min", "name": "Minangkabau" },
  "mk": { "code2": "mkd", "name": "Macedonian" },
  "ml": { "code2": "mal", "name": "Malayalam" },
  "mn": { "code2": "mon", "name": "Mongolian" },
  "mnc": { "code2": "mnc", "name": "Manchu" },
  "mni": { "code2": "mni", "name": "Manipuri" },
  "moh": { "code2": "moh", "name": "Mohawk" },
  "mos": { "code2": "mos", "name": "Mossi" },
  "mr": { "code2": "mar", "name": "Marathi" },
  "ms": { "code2": "msa", "name": "Malay" },
  "mt": { "code2": "mlt", "name": "Maltese" },
  "mus": { "code2": "mus", "name": "Creek" },
  "mwl": { "code2": "mwl", "name": "Mirandese" },
  "mwr": { "code2": "mwr", "name": "Marwari" },
  "my": { "code2": "mya", "name": "Burmese" },
  "myv": { "code2": "myv", "name": "Erzya" },
  "mzn": { "code2": "mzn", "name": "Mazanderani" },
  "na": { "code2": "nau", "name": "Nauru" },
  "nap": { "code2": "nap", "name": "Neapolitan" },
  "naq": { "code2": "naq", "name": "Nama" },
  "nb": { "code2": "nob", "name": "Norwegian Bokmål" },
  "nd": { "code2": "nde", "name": "North Ndebele" },
  "nds": { "code2": "nds", "name": "Low German" },
  "ne": { "code2": "nep", "name": "Nepali" },
  "new": { "code2": "new", "name": "Newari" },
  "ng": { "code2": "ndo", "name": "Ndonga" },
  "nia": { "code2": "nia", "name": "Nias" },
  "niu": { "code2": "niu", "name": "Niuean" },
  "nl": { "code2": "nld", "name": "Dutch" },
  "nmg": { "code2": "nmg", "name": "Kwasio" },
  "nn": { "code2": "nno", "name": "Norwegian Nynorsk" },
  "nnh": { "code2": "nnh", "name": "Ngiemboon" },
  "no": { "code2": "nor", "name": "Norwegian" },
  "nog": { "code2": "nog", "name": "Nogai" },
  "non": { "code2": "non", "name": "Old Norse" },
  "nqo": { "code2": "nqo", "name": "N'Ko" },
  "nr": { "code2": "nbl", "name": "South Ndebele" },
  "nso": { "code2": "nso", "name": "Northern Sotho" },
  "nus": { "code2": "nus", "name": "Nuer" },
  "nv": { "code2": "nav", "name": "Navajo" },
  "nwc": { "code2": "nwc", "name": "Classical Newari" },
  "ny": { "code2": "nya", "name": "Chichewa" },
  "nym": { "code2": "nym", "name": "Nyamwezi" },
  "nyn": { "code2": "nyn", "name": "Nyankole" },
  "nyo": { "code2": "nyo", "name": "Nyoro" },
  "nzi": { "code2": "nzi", "name": "Nzima" },
  "oc": { "code2": "oci", "name": "Occitan" },
  "oj": { "code2": "oji", "name": "Ojibwa" },
  "om": { "code2": "orm", "name": "Oromo" },
  "or": { "code2": "ori", "name": "Oriya" },
  "os": { "code2": "oss", "name": "Ossetian" },
  "osa": { "code2": "osa", "name": "Osage" },
  "ota": { "code2": "ota", "name": "Ottoman Turkish" },
  "pa": { "code2": "pan", "name": "Punjabi" },
  "pag": { "code2": "pag", "name": "Pangasinan" },
  "pal": { "code2": "pal", "name": "Pahlavi" },
  "pam": { "code2": "pam", "name": "Pampanga" },
  "pap": { "code2": "pap", "name": "Papiamento" },
  "pau": { "code2": "pau", "name": "Palauan" },
  "peo": { "code2": "peo", "name": "Old Persian" },
  "phn": { "code2": "phn", "name": "Phoenician" },
  "pi": { "code2": "pli", "name": "Pali" },
  "pl": { "code2": "pol", "name": "Polish" },
  "pon": { "code2": "pon", "name": "Pohnpeian" },
  "prg": { "code2": "prg", "name": "Prussian" },
  "pro": { "code2": "pro", "name": "Old Provençal" },
  "ps": { "code2": "pus", "name": "Pashto" },
  "pt": { "code2": "por", "name": "Portuguese" },
  "qu": { "code2": "que", "name": "Quechua" },
  "raj": { "code2": "raj", "name": "Rajasthani" },
  "rap": { "code2": "rap", "name": "Rapanui" },
  "rar": { "code2": "rar", "name": "Rarotongan" },
  "rm": { "code2": "roh", "name": "Romansh" },
  "rn": { "code2": "run", "name": "Rundi" },
  "ro": { "code2": "ron", "name": "Romanian" },
  "rof": { "code2": "rof", "name": "Rombo" },
  "rom": { "code2": "rom", "name": "Romany" },
  "root": { "code2": "root", "name": "Root" },
  "ru": { "code2": "rus", "name": "Russian" },
  "rup": { "code2": "rup", "name": "Aromanian" },
  "rw": { "code2": "kin", "name": "Kinyarwanda" },
  "rwk": { "code2": "rwk", "name": "Rwa" },
  "sa": { "code2": "san", "name": "Sanskrit" },
  "sad": { "code2": "sad", "name": "Sandawe" },
  "sah": { "code2": "sah", "name": "Sakha" },
  "sam": { "code2": "sam", "name": "Samaritan Aramaic" },
  "saq": { "code2": "saq", "name": "Samburu" },
  "sas": { "code2": "sas", "name": "Sasak" },
  "sat": { "code2": "sat", "name": "Santali" },
  "sba": { "code2": "sba", "name": "Ngambay" },
  "sbp": { "code2": "sbp", "name": "Sangu" },
  "sc": { "code2": "srd", "name": "Sardinian" },
  "scn": { "code2": "scn", "name": "Sicilian" },
  "sco": { "code2": "sco", "name": "Scots" },
  "sd": { "code2": "snd", "name": "Sindhi" },
  "se": { "code2": "sme", "name": "Northern Sami" },
  "seh": { "code2": "seh", "name": "Sena" },
  "sel": { "code2": "sel", "name": "Selkup" },
  "ses": { "code2": "ses", "name": "Koyraboro Senni" },
  "sg": { "code2": "sag", "name": "Sango" },
  "sga": { "code2": "sga", "name": "Old Irish" },
  "sh": { "code2": "hbs", "name": "Serbo-Croatian" },
  "shi": { "code2": "shi", "name": "Tachelhit" },
  "shn": { "code2": "shn", "name": "Shan" },
  "si": { "code2": "sin", "name": "Sinhala" },
  "sid": { "code2": "sid", "name": "Sidamo" },
  "sk": { "code2": "slk", "name": "Slovak" },
  "sl": { "code2": "slv", "name": "Slovenian" },
  "sli": { "code2": "sli", "name": "Lower Silesian" },
  "sm": { "code2": "smo", "name": "Samoan" },
  "sma": { "code2": "sma", "name": "Southern Sami" },
  "sn": { "code2": "sna", "name": "Shona" },
  "snk": { "code2": "snk", "name": "Soninke" },
  "so": { "code2": "som", "name": "Somali" },
  "sog": { "code2": "sog", "name": "Sogdian" },
  "sq": { "code2": "sqi", "name": "Albanian" },
  "sr": { "code2": "srp", "name": "Serbian" },
  "srn": { "code2": "srn", "name": "Sranan Tongo" },
  "srr": { "code2": "srr", "name": "Serer" },
  "ss": { "code2": "ssw", "name": "Swati" },
  "ssy": { "code2": "ssy", "name": "Saho" },
  "st": { "code2": "sot", "name": "Southern Sotho" },
  "su": { "code2": "sun", "name": "Sundanese" },
  "suk": { "code2": "suk", "name": "Sukuma" },
  "sus": { "code2": "sus", "name": "Susu" },
  "sux": { "code2": "sux", "name": "Sumerian" },
  "sv": { "code2": "swe", "name": "Swedish" },
  "sw": { "code2": "swa", "name": "Swahili" },
  "swb": { "code2": "swb", "name": "Comorian" },
  "syc": { "code2": "syc", "name": "Classical Syriac" },
  "syr": { "code2": "syr", "name": "Syriac" },
  "ta": { "code2": "tam", "name": "Tamil" },
  "te": { "code2": "tel", "name": "Telugu" },
  "tem": { "code2": "tem", "name": "Timne" },
  "teo": { "code2": "teo", "name": "Teso" },
  "ter": { "code2": "ter", "name": "Tereno" },
  "tet": { "code2": "tet", "name": "Tetum" },
  "tg": { "code2": "tgk", "name": "Tajik" },
  "th": { "code2": "tha", "name": "Thai" },
  "ti": { "code2": "tir", "name": "Tigrinya" },
  "tig": { "code2": "tig", "name": "Tigre" },
  "tiv": { "code2": "tiv", "name": "Tiv" },
  "tk": { "code2": "tuk", "name": "Turkmen" },
  "tkl": { "code2": "tkl", "name": "Tokelau" },
  "tl": { "code2": "tgl", "name": "Tagalog" },
  "tlh": { "code2": "tlh", "name": "Klingon" },
  "tli": { "code2": "tli", "name": "Tlingit" },
  "tmh": { "code2": "tmh", "name": "Tamashek" },
  "tn": { "code2": "tsn", "name": "Tswana" },
  "to": { "code2": "ton", "name": "Tongan" },
  "tog": { "code2": "tog", "name": "Nyasa Tonga" },
  "tpi": { "code2": "tpi", "name": "Tok Pisin" },
  "tr": { "code2": "tur", "name": "Turkish" },
  "trv": { "code2": "trv", "name": "Taroko" },
  "ts": { "code2": "tso", "name": "Tsonga" },
  "tsi": { "code2": "tsi", "name": "Tsimshian" },
  "tt": { "code2": "tat", "name": "Tatar" },
  "tum": { "code2": "tum", "name": "Tumbuka" },
  "tvl": { "code2": "tvl", "name": "Tuvalu" },
  "tw": { "code2": "twi", "name": "Twi" },
  "twq": { "code2": "twq", "name": "Tasawaq" },
  "ty": { "code2": "tah", "name": "Tahitian" },
  "tyv": { "code2": "tyv", "name": "Tuvinian" },
  "tzm": { "code2": "tzm", "name": "Central Atlas Tamazight" },
  "udm": { "code2": "udm", "name": "Udmurt" },
  "ug": { "code2": "uig", "name": "Uyghur" },
  "uga": { "code2": "uga", "name": "Ugaritic" },
  "uk": { "code2": "ukr", "name": "Ukrainian" },
  "umb": { "code2": "umb", "name": "Umbundu" },
  "ur": { "code2": "urd", "name": "Urdu" },
  "uz": { "code2": "uzb", "name": "Uzbek" },
  "vai": { "code2": "vai", "name": "Vai" },
  "ve": { "code2": "ven", "name": "Venda" },
  "vi": { "code2": "vie", "name": "Vietnamese" },
  "vo": { "code2": "vol", "name": "Volapük" },
  "vot": { "code2": "vot", "name": "Votic" },
  "vun": { "code2": "vun", "name": "Vunjo" },
  "wa": { "code2": "wln", "name": "Walloon" },
  "wae": { "code2": "wae", "name": "Walser" },
  "wal": { "code2": "wal", "name": "Wolaytta" },
  "war": { "code2": "war", "name": "Waray" },
  "was": { "code2": "was", "name": "Washo" },
  "wbp": { "code2": "wbp", "name": "Warlpiri" },
  "wo": { "code2": "wol", "name": "Wolof" },
  "xal": { "code2": "xal", "name": "Kalmyk" },
  "xh": { "code2": "xho", "name": "Xhosa" },
  "xog": { "code2": "xog", "name": "Soga" },
  "yao": { "code2": "yao", "name": "Yao" },
  "yap": { "code2": "yap", "name": "Yapese" },
  "yav": { "code2": "yav", "name": "Yangben" },
  "ybb": { "code2": "ybb", "name": "Yemba" },
  "yi": { "code2": "yid", "name": "Yiddish" },
  "yo": { "code2": "yor", "name": "Yoruba" },
  "yue": { "code2": "yue", "name": "Cantonese" },
  "za": { "code2": "zha", "name": "Zhuang" },
  "zap": { "code2": "zap", "name": "Zapotec" },
  "zbl": { "code2": "zbl", "name": "Blissymbols" },
  "zen": { "code2": "zen", "name": "Zenaga" },
  "zgh": { "code2": "zgh", "name": "Standard Moroccan Tamazight" },
  "zh": { "code2": "zho", "name": "Chinese" },
  "zh-Hans": { "code2": "zho", "name": "Simplified Chinese" },
  "zh-Hant": { "code2": "zho", "name": "Traditional Chinese" },
  "zu": { "code2": "zul", "name": "Zulu" },
  "zun": { "code2": "zun", "name": "Zuni" },
  "zxx": { "code2": "zxx", "name": "No linguistic content" },
  "zza": { "code2": "zza", "name": "Zaza" }
};

module.exports = ISO_MAP;
